//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pomodoro_App.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("411e08dd-f687-436d-ab7c-82880a9bdefe")]
        public string clientId {
            get {
                return ((string)(this["clientId"]));
            }
            set {
                this["clientId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.microsoftonline.com/common/oauth2/nativeclient")]
        public string redirectUri {
            get {
                return ((string)(this["redirectUri"]));
            }
            set {
                this["redirectUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pawel.jakubowski@all-for-one.com")]
        public string ATLASSIAN_USERNAME {
            get {
                return ((string)(this["ATLASSIAN_USERNAME"]));
            }
            set {
                this["ATLASSIAN_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ATATT3xFfGF0bw6mmPZwwKhmWUztWssVPDGwPeN9YqXMHGft62X2Twmdcxc55i15COqPHrqpaSGsyrneo" +
            "gpNMkTw-Wex7iLSsUfZpTVPBiA-gpAzHLkMkuoOvOPLaL9JLi44tTRb1foqQD6vrh655fignD7zgXah7" +
            "AMNFFRkqDNx0xQ8XXYu8Q8=F7703639")]
        public string ATLASSIAN_API_KEY {
            get {
                return ((string)(this["ATLASSIAN_API_KEY"]));
            }
            set {
                this["ATLASSIAN_API_KEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("all41")]
        public string DOMAIN {
            get {
                return ((string)(this["DOMAIN"]));
            }
            set {
                this["DOMAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("605c3fc78efc9b0070580f35")]
        public string ATLASSIAN_ACCOUNTID {
            get {
                return ((string)(this["ATLASSIAN_ACCOUNTID"]));
            }
            set {
                this["ATLASSIAN_ACCOUNTID"] = value;
            }
        }
    }
}
